### ISSUE TITLE
Appendix: Example Key Value Measures  - Unrealized Value Market share

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#10]
In de KVM Unrealized Value section is de beschrijving  van market share in het negatief  'the relative percentage of the market **_not_** controlled by the product...' Ik neem aan dat dat gedaan is omdat het in deze context onder Unrealized Value behoort. 

De vertaling is in het Nederlands is in het positieve licht gesteld, het beschrijft de definitie market share  als : 'Dit is het aandeel dat een aanbieder van een goed of dienst heeft in de totale omzet op de betreffende markt in een bepaalde periode'

Zou het beter zijn om het net als in het engels in negatief te beschrijven daar het uiteindelijk in de context van Unrealized Value past?

P.S. apologies for my very bad description in Dutch, I never write in Dutch anymore so need to think LOL!

**Comment by sjoerdly** [comment]
Eens Glaudia. Ik vind wel ook dat de titel van de KVM aangepast moet worden, en doe dit heel rebels dan vast in de vertaling. Omdat het gaat om de gap vanuit de UV zoals je schrijft, moet het iets van 'marktpotentie' zijn. Het marktaandeel is wat je al hebt. Marktpotentie is wat je mogelijk (extra) kunt behalen mits je de juiste waarde toevoegt aan je Product.

PS ik laat deze nog even open omdat Ik het ook belangrijk vind om @macluky 's inzichten en ervaring mee te nemen.

**Comment by macluky** [comment]
Ja de engelse is zelfs fout. Market Share is wat je al hebt en bij unrealized je juist de ruimte bepalen die er nog is.

**Comment by sjoerdly** [comment]
Dus je bent het eens met onze afwijkende 'vertaling' @macluky ? of heb je nog alternatieven voor 'marktpotentie' wellicht

**Comment by macluky** [comment]
Ja deze is prima, beter dan de engelse

On 18 Jan 2021, at 11:42, Sjoerd Kranendonk <notifications@github.com> wrote:


Dus je bent het eens met onze afwijkende 'vertaling' @macluky <https://github.com/macluky> ? of heb je nog alternatieven voor 'marktpotentie' wellicht

**Comment by sjoerdly** [comment]
Aangezien we het eens zijn, kan deze gesloten :)
