### ISSUE TITLE
Appendix: Example Key Value Measures: Inconsistent gebruik van 'enzovoort' en 'etc'

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#11]
Ik zag in het engels dat er soms gebruik wordt gemaakt van verschillende woorden mbt enzovoort. Bijvoorbeeld: 'and so forth' 'and so on'.  In de nederlandse vertaling wordt soms 'enzovoort' gebruikt en andere keren 'etc' . Vraag me af of het beter zou zijn in nederlands om consistent te zijn? Of is dit opzettelijk gedaan zodat er meer variatie is?  . Zie voorbeeld:

![image](https://user-images.githubusercontent.com/52327049/104853474-0c378c00-58f9-11eb-93ef-c12c467350f6.png)

**Comment by sjoerdly** [comment]
Interessante vraag. In het engels is het volgens mij gebruikelijk om and so on and so forth af te wisselen. In het nederlands is enzovoort (and so forth) wel gebruikelijk maar en zo verder (wat meer is zoals and so on) niet. Wel zijn enzovoort en enzovoorts beiden te gebruiken, wat de subtiele afwisseling zou kunnen spiegelen. Maar wellicht ook meer leest als slordigheid/inconsistentie.

Door dit te proberen na te zoeken wat het advies is (afwisselen of consistentie voorkeur) kwam ik er wel achter dat er geen komma voor de afsluiter van een opsomming hoeft (behalve bij lange opsommingsdelen). Dus weer wat geleerd. Zie https://taaladvies.net/taal/advies/vraag/466/komma_voor_ed_enz_of_etc_aan_het_einde_van_een_opsomming/

Voor nu heb ik gekozen voor consistentie. Omdat in het engels et cetera ook bestaat maar dat is hier niet gebruikt, dus dan is dat wel echt een andere stijl.

**Comment by macluky** [comment]
Bij de Product Samurai hadden we op een gegeven moment een lijst van woorden en situaties die we consistent gebruikten. Hebben we hier ook al iets dergelijks gedaan?

**Comment by sjoerdly** [comment]
@macluky nope, als je iets tegenkomt is dat een goed begin om zoiets te starten. Maak gerust een 'consistentielijst.md' aan of iets dergelijks.

**Comment by sjoerdly** [comment]
Volgens mij is deze nu afgehandeld, er is een apart issue voor de woordenlijst en de lijst is inmiddels ook aangemaakt. De 'en zo voort' consistentie waar dit item echt over gaat is inmiddels opgelost.
