### ISSUE TITLE
Appendix: Example Key Value Measures - Klein type foutje: 'zin' ivp 'zijn'

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#12]
Klein type foutje in de appendix - begriipen wat waardevol is - Uitkomsten

'zin' ipv 'zijn': 

- Uitkomsten. Dit zijn de wensen die een klant of gebruiker van een product ervaart. Ze vertegenwoordigen een nieuwe of verbeterde mogelijkheid die eerder onbereikbaar was voor de klant of gebuiker. Voorbeelden zijn sneller dan voorheen kunnen reizen naar een bestemming, of meer geld verdienen of sparen dan eerder mogelijk was. Uitkomsten kunnen ook negatief **_zin,_**

**Comment by sjoerdly** [comment]
fixed, ook nog een keer gebuiker -> gebruiker. typoooooos
