### ISSUE TITLE
Appendix: Example Key Value Measures - translation of 'adapt, adaptation, adaptability'

### ISSUE THREAD

**Issue by dennmans** [ScrumFacilitators/EBM-Gids-NL#13]
Ik zie dat in de eerste paragraaf 'toepasbaar' en 'verandervermogen' gebruikt worden als vertaling voor adaptability en ability to improve.  Omdat dit pilaren van Scrum zijn, zou ik 'aanpasbaar' en 'aanpassingsvermogen' gebruiken.

**Comment by sjoerdly** [comment]
ability to improve heb ik nu alvast aangepast naar _verbetervermogen_. het is nl niet ability to _adapt_. De eerst zin moet even met iets meer aandacht herschreven worden, maar ben het eens met de suggestie (al is de inhoud hetzelfde, de gesuggereerde woordkeuze voegt hier wel iets toe imho)

**Comment by sjoerdly** [comment]
@dennmans voel je vrij om vast wat voorstellen en suggesties voor dit soort belangrijke termen toe te voegen in #15  want dat scheelt uiteindelijk discussie en is goed voor consistentie binnen deze vertaling en met evt ander gerelateerd materiaal (scrumgids, etc)

**Comment by sjoerdly** [comment]
De zin met aanpasbaar herschreven. Andere woordkeuze en directe betekenis (encourage niet overgenomen) maar strekking is denk ik betere zin en leest beter dan "Om aanpasbaarheid aan te moedigen, ...."
