### ISSUE TITLE
Hoofdletters in titels

### ISSUE THREAD

**Issue by dennmans** [ScrumFacilitators/EBM-Gids-NL#14]
In https://github.com/ScrumFacilitators/EBM-Gids-NL/blob/main/EBM%20Gids%202020_1%20NL.md#ebm-helpt-organisaties-in-een-complexe-wereld-om-empirisme-te-gebruiken-in-de-zoektocht-naar-hun-doelen wordt de Engelse hoofdletterconventie gebruikt voor titels.  In het Nederlands gebruik je alleen hoofdletters in het eerste woord van een titel en woorden die anders ook een hoofdletter krijgen (eigennamen, merken, instellingen).  'Gids' zou nog kunnen omdat het een vertaling is van een Engelse titel maar beter is 'Evidence Based Management gids'.  Ik baseer dit op: https://taaladvies.net/taal/advies/tekst/98/hoofdletters_bij_titels_van_boeken_liedjes_films_ed_algemeen/

**Comment by sjoerdly** [comment]
Goeie! ik zit zelf soms zo in het engels dat me dit niet meer opvalt. Moet even goed door het hele document heen nagelopen worden en aangepast. TODO!

**Comment by dennmans** [comment]
Ik ken het probleem!  Mijn eerste taal is Engels en ik heb op late leeftijd en bewust onbekwaam Nederlands moeten leren.

**Comment by nicknijenhuis** [comment]
Het viel me persoonlijk ook al op. Geen fan van die hoofdletters, niet in het Nederlands en niet in het Engels. Ter info, in het Engels hoeft het ook niet, het gebeurt wel regelmatig, https://www.dailywritingtips.com/rules-for-capitalization-in-titles/

**Comment by sjoerdly** [comment]
Ja ik heb in eerste instantie gewoon overgenomen van de engelse stijl. Dit is een van de dingen waar het prima is om daar van af te wijken, niet alleen omdat het beter nederlands is, maar ook omdat het gewoon geen waarde toevoegt aan de inhoud. 

Ook op andere plekken mogen we subtiel afwijken, wanneer dat een beter eindproduct oplevert. bv consistenter met cursiefs omgaan, overal de KVA's voluit schrijven (afko's lezen beroerd) etc.

**Comment by sjoerdly** [comment]
Meeste is nu aangepast. Graag nog een check of ik niets heb gemist. En wat jullie vinden van 'Hypothesen, Experimenten, Features en Requirements' - dit zijn allemaal termen die in het opvolgende stuk tekst worden uitgelegd. Wel of niet met hoofdletter?

**Comment by sjoerdly** [comment]
Besloten deze niet met hoofdletter te doen. zijn geen eigennamen zoals Key Value Areas wel is. Daarmee deze issue ook voltooid.
