### ISSUE TITLE
Type foutje in Ability to Innovate (A21) section

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#16]
Klein type foutjes in the  Ability to Innovate (A21) section. 

moetn ipv moeten

>Voorbeeld: Een verscheidenheid aan dingen kan een organisatie beletten om nieuwe mogelijkheden en waarde te leveren: te veel tijd kwijt zijn aan rechtzetten van lage productkwaliteit, meerdere productvariantien **_moetn_**

en 

di ivp die
De A2I verbeteren helpt een organisatie om effectiever te worden in het omzetten van verricht werk naar waarde **_di_** zij levert met haar producten of diensten aan klanten of gebruikers.

**Comment by sjoerdly** [comment]
Fixed! ook de zin waar 'di' typfout in zat herschreven omdat het dan beter leest in NL (vind ik zelf)
