### ISSUE TITLE
Type foutje in Time to Market section - verbeterd ivp verbetert?

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#17]
Wanneer T2M verbetert, **_verbeterd_** ook de frequentie waarmee een organisatie haar CV kan mogelijk kan aanpassen.

Moet de 'verbeterd' niet ook in onvoltooid tegenwoordige tijd worden gespeld? Dus 'verbetert'.

**Comment by sjoerdly** [comment]
typo fixed!
