### ISSUE TITLE
Time To Market section -  woord 'is'  

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#18]
In de Time to Market Section, in het voorbeeld, leest de volgende zin niet lekker door het woordje 'is' voor het woord 'levert'

Voorbeeld: Het verminderen van de functies in een productversie kan de T2M drastisch verbeteren; de kleinst mogelijke release **_is levert_** ten minste een incrementele waardeverbetering aan een specifiek deel van de klanten/gebruikers van het product.

Als ik naar het engels kijk zou beter zijn of het woord 'is' helemaal te verwijderen?  Of als we het meer letterlijk willen vertalen van het engels het te veranderen naar 

Voorbeeld: Het verminderen van de functies in een productversie kan de T2M drastisch verbeteren; de kleinst mogelijke release is een release dat ten minste een incrementele waardeverbetering  levert aan een specifiek deel van de klanten/gebruikers van het product.

**Comment by sjoerdly** [comment]
Goed gevonden, herschrijf-leftover.
