### ISSUE TITLE
Unrealized Value (UV) section -  'potentiele' of 'potentiële' (inconsistency)

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#19]
In de meeste plaatsen wordt het woord 'potentiële' gebruikt. Echter in sommige plaatsen wordt het gespeld als potentiele, dus kan als inconsistent worden gezien. Zie hieonder:

Unrealized Value (UV) section,  'potentiele' ipv 'potentiële'

>Bijvoorbeeld: *Een product kan een lage CV hebben omdat het een vroege versie is die gebruikt wordt om de markt te testen en een erg hoge UV die aangeeft dat er een groot marktpotentieel is. Het is waarschijnlijk gerechtvaardigd om een poging te doen om CV te verhogen, gegeven de **_potentiele_** winst, door te investeren in het product ondanks dat het product momenteel geen hoge CV oplevert. *

EBM Framework image 

Spelling het framework image is  potentiele

**Comment by sjoerdly** [comment]
Tekst aangepast, afbeelding moet nog

**Comment by sjoerdly** [comment]
afbeelding ook aangepast (commit volgt)
