### ISSUE TITLE
Current Value (CV) section - is 'afwegen' of 'het in acht nemen' een betere vertaling voor 'considering' in deze context?

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#20]
"Considering CV from several perspectives will give you a better understanding of your challenges and opportunities"  woord considering is vertaald in het Nederlands naar 'wegen'. Vraag me af of in deze context het beter zou zijn het te vertalen met bijvoorbeeld ' Het afwegen van' of 'Het in acht nemen van'. Zie heironder de huidige vertaling 

> Voorbeeld: *Terwijl winst, een manier om tevredenheid van investeerders te meten, je de economische impact geeft van de waarde die je wilt leveren, zal weten hoe tevreden klanten zijn met hun aankoop je meer inzicht geven over wat je kunt verbeteren om deze klanten te behouden. Wanneer je klanten weinig alternatieven hebben voor jouw product, kun je hoge winst behalen, zelfs met een lage klanttevredenheid. **_Het wegen van CV vanuit verschillende invalshoeken_** zal je een beter begrip geven van je uitdagingen en kansen.

**Comment by sjoerdly** [comment]
Na een paar experimentjes met google translate kom ik uit op 'rekening houden met' wat volgens mij het beste past in deze context. 

Thanks voor het uitdagen, ook al neem ik je suggestie in dit geval niet letterlijk over, de vertaling is er wel beter door (vind ik zelf dan he).
