### ISSUE TITLE
EBM Framework image - momenteel

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#21]
In de EBM Framework image 'Welke waarde wordt op dit moment door de organisatie geleverd".  Zat te denken dat mischien het woord momenteel mischien beter klinkt daar het korter is. Maar is een persoonlijke smaak kwestie, dus is gewoon maar een suggestie. 

'Welke waarde wordt momenteel door de organisatie geleverd".

**Comment by sjoerdly** [comment]
Overgenomen.
