### ISSUE TITLE
Use of Capital letters in the 'Experimentenlus' 

### ISSUE THREAD

**Issue by Studiesmurf** [ScrumFacilitators/EBM-Gids-NL#41]
Page 4:

In the 'Experimentenlus' - quadrant 'Aanpassen', the last word 'Aanpassen' should be 'aanpassen'..

Also note the use of too many capital letters in the loop and the rest of the image.

**Comment by sjoerdly** [comment]
We passen nu alleen 'aanpassen' aan. 

Of de verschillende soorten doelen wel of niet met hoofdletters blijven is een aparte discussie.
