### ISSUE TITLE
Subtitel 1e pagina - suggestie herschrijving en alignment issue

### ISSUE THREAD

**Issue by Studiesmurf** [ScrumFacilitators/EBM-Gids-NL#42]
Hello.

De subtitel klinkt heel raar, maar ook is hij niet aligned. ( Voor de mooi wel even doen ;) )
Én ik zou er **"Optimale waardelevering in onzekere situaties"** van maken, klinkt net even iets soepeler. :)

**Comment by sjoerdly** [comment]
Alignment fixed. Voor de vertalingsaanpassing, de originele subtitel is: 

**Improving Value Delivery under Conditions of Uncertainty**

Het woord improving is wat anders dan optimale. Daarom gekozen voor 'betere'. 'Verbeteren van' zou ook kunnen.

**Verbeteren van waardelevering in onzekere omstandigheden** zou misschien ook al minder gek zijn? 

Situaties past m.i. ook niet helemaal, omdat dit geen recht doet aan het continue van toepassing zijn van het framework. Een situatie klinkt niet voortdurend genoeg, maar meer iets voorbijgaands. Omstandigheden kunnen ook voorbijgaan, maar hebben minder associatie voor mij met korte tijdsduur dan situatie.

**Comment by sjoerdly** [comment]
Voor nu aangepast naar Verbeteren van waardelevering in onzekere omstandigheden
