### ISSUE TITLE
voetnoot pagina 1 (scrum.org) is nog engelstalig

### ISSUE THREAD

**Issue by Studiesmurf** [ScrumFacilitators/EBM-Gids-NL#43]
"This publication.."etc etc is Engels. 
De gids zelf is in het Nederlands, dus voor de consistentie zou ik deze voetnoot óók NL maken.

**Comment by sjoerdly** [comment]
Bewust niet gedaan in eerste instantie. Inderdaad netter om wel te doen. 

Ff kijken waar het in de prioriteiten valt.
