### ISSUE TITLE
P6 Huidige Toestand = Current State = Huidige Situatie?

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/EBM-Gids-NL#54]
P6 Voortgang maken in…

Huidige Toestand = Current State = Huidige Situatie?

De eerste stap in de richting van een Strategisch Doel is het begrijpen van je _Huidige Toestand_, zodat je de aandacht kunt richten op mogelijke verbeteringen.

The first step in the journey toward a Strategic Goal is understanding your _Current State_ to frame your thinking about where and how you need to improve.

Split off from #52

**Comment by glaudia** [comment]
@sjoerdly Misschien moeten we hier eigenlijk wat meer letterlijk vertalen in deze context? Bijvoorbeeld 'Huidige staat'. Dit gebaseerd op wat referentie materiaal zoals bijvoorbeeld:

https://www.youweagency.nl/e-commerce/de-huidige-staat-van-e-commerce-nederland
https://www.hollandgold.nl/nieuws/de-huidige-staat-en-toekomst-van-de-amerikaanse-economie/
https://context.reverso.net/vertaling/nederlands-engels/toekomstige+staat
https://www.lucidchart.com/pages/nl/sjablonen/voorbeeld-van-serviceblauwdruk-met-huidige-en-toekomstige-staat

**Comment by sjoerdly** [comment]
Ja dat is ook waar. Ik vind dat zelf gewoon niet zo'n duidelijk woord maar is wel correct lijkt het. Ik vind persoonlijk huidige toestand (de toestand waar het bedrijf/product zich in bevindt) beter passen. 

Ik beweeg wel mee aangezien ik in de minderheid ben 😅

**Comment by glaudia** [comment]
Toestand is ook goed hoor :-)

**Comment by sjoerdly** [comment]
Na enige twijfel toch houden bij toestand tenzij er meer stemmen en argumenten voor 'staat' komen.
