### ISSUE TITLE
P8 EBM bevat vier…. - geschiktheid -> vermogen 

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/EBM-Gids-NL#57]
P8 EBM bevat vier….

Eerste alinea is niet vertaald. Voorstel voor de tekst.

Naast het gebruik van hypothesen en experimenten om doelen te bereiken, voorziet EBM in een aantal inzichten op waarde en het vermogen van de organisatie om waarde te leveren. Deze inzichten worden Key Value Areas (KVA’s) genoemd. Deze gebieden onderzoeken de doelstellingen van de organisatie (Unrealized Value), de huidige staat van de organisatie ten opzichte van die doelstellingen (Current Value), de (flexibiliteit en) effectiviteit van de organisatie bij het leveren van waarde (Time-to-Market) en de effectiviteit van de organisatie in het leveren van waarde (Ability-to-Innovate).

In addition to using hypotheses and experiments to move toward goals, EBM provides a set of perspectives on value and the organization’s ability to deliver value. These perspectives are called Key Value Areas (KVAs). These areas examine the goals of the organization (Unrealized Value), the current state of the organization relative to those goals (Current Value), the responsiveness of the organization in delivering value (Time-to-Market), and the effectiveness of the organization in delivering value (Ability-to-Innovate).

afgesplitst van #52

**Comment by sjoerdly** [comment]
De bug is gefixed, maar nu kunnen we nog de alinea verbeteren met sommige van maarten's suggesties in de vertaling....

Dit is het verschil tussen onze vertaling (rood, links) en de nieuwe gesuggereerde vertaling van Maarten (groen, rechts)

![Image](https://github.com/ScrumFacilitators/EBM-Gids-NL/assets/1508446/f57ec277-67ba-4e88-adb0-b65df7416846)

Ik vind 'het vermogen om waarde te leveren' mooier dan geschiktheid.

Ook vind ik het gebruik van doelstellingen hier mooier dan doelen, maar dit levert misschien inconsistentie op met andere plekken.

Net als in het andere issue met toestand vs staat, hier ook staat aanhouden?

Verder zou ik de suggesties niet willen overnemen. Andere argumenten? @glaudia ?

**Comment by glaudia** [comment]
Ja, vind 'vermogen' ook beter dan 'geschiktheid'. Als we het ergens anders ook in 'staat' hebben veranderd dan zou ik dat hier ook doen, gewoon uit consistency. 

Nou mbt doelen vs doelstellingen, dat is een beetje tricky daar ze officieel een verschillende betekenis hebben in het nederlands.

**Comment by sjoerdly** [comment]
Hmm ik ga vermogen dan inderdaad doorvoeren en zal nog ff kijken of we ergens anders nog geschiktheid ook kunnen vervangen door vermogen.

In de andere issue #54 ben ik toch niet overtuigd van 'staat' en ook hier leest het weer gek als ik de alinea doorlees. Die laat ik even.

De doelstellingen moeten we dan ook maar laten, want dat is nu niet zeker of dat ook is wat er bedoeld wordt, en doelen is wat algemener denk ik en dekt daardoor sowieso ook de lading.

Voor nu dus alleen 'vermogen' ipv 'geschiktheid'. Op vier plekken vervangen.
