### ISSUE TITLE
Comments/ inputs on section 'Doel van de EBM Gids'

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#6]
Should the word 'continue' be 'continu' instead?

'Evidence-Based Management (EBM) is een empirische aanpak die organisaties helpt met **continue** verbeteren van' 

So it would be 
'Evidence-Based Management (EBM) is een empirische aanpak die organisaties helpt met  het continu verbeteren van' 

As I have not been living in the NL for years, it could be that the word continue is fine in Dutch now, so ignore me if I have it wrong!

**Comment by sjoerdly** [comment]
Fixed, goed gevonden!
