### ISSUE TITLE
Pagina 11 Ability to Innovate (A2I) - belemmeringen -> impediments en voorkomt->beperkt

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/EBM-Gids-NL#60]
Pagina 11 Ability to Innovate (A2I)

Wanneer functinaliteit van…. Te installeren.

voor het onderhoud of _overwinnen van belemmeringen_, waardoor
voor het onderhoud of _oplossen van impediments_, waardoor

door alles wat _voorkomt_ dat gebruikers of klanten profiteren
door alles wat _beperkt_ dat gebruikers of klanten profiteren

Wanneer functionaliteit van lage waarde en systemische belemmeringen zich opstapelen, wordt meer en meer tijd en geld verbruikt voor het onderhoud of _overwinnen van belemmeringen_, waardoor de beschikbare innovatiecapaciteit wordt beperkt. Tevens wordt de A2I verminderd door alles wat _voorkomt_ dat gebruikers of klanten profiteren van innovatie, zoals (nieuwe versies van) producten die moeilijk zijn om in elkaar te zetten of te installeren.

As low-value features and systemic impediments accumulate, more budget and time are consumed maintaining the product or overcoming impediments, reducing its available capacity to innovate. In addition, anything that prevents users or customers from benefiting from innovation, such as hard to assemble/install products or new versions of products, will also reduce A2I.

afgesplitst van #52

**Comment by sjoerdly** [comment]
Deze stukken lezen idd niet lekker. Ik denk echter dat er andere wijzigingen nodig zijn om dit duidelijker te maken, waar Maarten's suggsties wel een aanzet toe vormen.

Het woord belemmeringen wordt in de zin eerder ook al gebruikt dus die zou ik willen behouden. Misschien wel 'weghalen' of 'oplossen' in plaats van overwinnen, wat inderdaad geen veelgebruikte nederlandse constructie is op deze manier.

Voor de 2e suggestie:
Tevens wordt de A2I aangetast door elke beperking die als gevolg heeft dat gebruikers of klanten minder kunnen profiteren van innovatie.

Meningen gevraagd!

**Comment by glaudia** [comment]
Suggestie om het wat simpeler te maken:

_Wanneer minder waardevolle functionaliteit en systematische belemmeringen opeenstapelen, kost het steeds meer tijd en geld om deze belemmeringen op te lossen. Dit betekent dat er minder ruimte is voor innovatie_

@sjoerdly ik snapte jouw 2e suggestie niet helemaal, het voelt dat het andersom vertaald is. Dat er beperkingen zijn en dat daardoor klanten geen voordeel kunnen maken. Dus de verminderde A21 is de 'cause' en klanten kunnen het niet gebruiken is het 'gevolg' Maar in de engelse tekst lees ik dat andersom (en zo is het ook vertaald in de originele vertaling). Maar het kan dat ik dit verkeerd lees, ik lees niet zo heel veel nederlands meer tegenwoordig ;-)

Als suggestie had it voor de 2e deel: 

_Daarnaast zal alles wat gebruikers of klanten ervan weerhoudt te profiteren van innovatie, zoals moeilijk in elkaar te zetten of te installeren van producten of nieuwe versies, ook de A2I verminderen._

**Comment by sjoerdly** [comment]
Ah ja, goed om even terug naar de oorspronkelijke tekst te kijken, en daarvan de essentie te vertalen, ipv al te letterlijk. 

Mooie suggesties @glaudia !

**Comment by sjoerdly** [comment]
Doorgevoerd, met alleen de oorspronkelijke 'minder capaciteit over blijft' in plaats van de gesuggereerde 'minder ruimte is'.

Uiteindelijke tekst:

Wanneer minder waardevolle functionaliteit en systematische belemmeringen opeenstapelen, kost het steeds meer tijd en geld om deze belemmeringen op te lossen. Dit betekent dat er minder capaciteit over blijft voor innovatie. Daarnaast zal alles wat gebruikers of klanten ervan weerhoudt te profiteren van innovatie, zoals moeilijk in elkaar te zetten of te installeren producten of nieuwe versies, ook de A2I verminderen.
