### ISSUE TITLE
find best translation of “Organizational Capability”

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/EBM-Gids-NL#7]
Currently, the translation is "Organisatiegeschiktheid".

Alternatives are:

- "Organisatorische mogelijkheid"
- "Organisatievermogen" (google translate)
- "Organisatorisch vermogen" (google translate)
- "Organisatiecompetenties" (dank @glaudia)

Please add suggestions or arguments for the best version.

I'm currently leaning towards changing to "organisatorisch vermogen" although I like 'geschiktheid' as well.

PS I don't know why I write this in English. Aangezien iedereen die hier een mening over heeft waarschijnlijk gewoon Nederlands kan. ;-)

**Comment by glaudia** [comment]
hoi hoi 

sorry, I will be writing in English as it goes faster ha ha ha ha. If I have to switch to Dutch I have to think and it is too early for that ;-)

Anyway such a tricky one!!

I like organisatorisch vermogen, I prefer it over organisatie vermogen as that could be confused with the financial aspect (financieel vermogen)

Anyway went to Dutch websites from other organisations to see if they use certain words to express organisation capabilities. I did come accross: 'organisatiecompetenties'. Where they explain:  'Een competentie is het vermogen om iets te kunnen en daarvoor dienen verschillende zaken aanwezig te zijn' Examples of websites where I found this to put it in context:
https://hora.surf.nl/index.php/Ontwikkelen_van_organisatiecompetenties
http://vianovaarchitectura.nl/profiles/blogs/ontwikkelen-van-organisatiecompetenties

**Comment by sjoerdly** [comment]
Thanks!

Organisatiecompetenties klinkt ook goed. Another contender!

**Comment by sjoerdly** [comment]
Voor nu geland op organisatiecompetenties. 

TODO: Moet nog wel even in de lopende tekst overal goed nagekeken worden, dat er niet nog op plekken geschiktheid staat waar in het engels capability stond.

**Comment by sjoerdly** [comment]
closed as decision is made. Will make a new task to check for consistency in new backlog
