### ISSUE TITLE
Appendix: Example Key Value Measures - klein tik foutje ''peride' ipv 'periode

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#8]
Appendix: Example Key Value Measures 

In de sectie Gemiddelde Reparatietijd is een klein  tik foutje, peride ipv periode

'De gemiddelde peride die verstrijkt tussen het moment dat een probleem is ontdekt en dat het is opgelost. '

**Comment by sjoerdly** [comment]
Fixed, also fixed typo 'datgenene' -> 'datgene' in another spot.

**Comment by sjoerdly** [comment]
strange, cannot find the change for datgenene anymore. Must have been a glitch or I introduced it myself (and fixed it). nothing to see here. move along ;-)
