### ISSUE TITLE
Appendix: Example Key Value Measures- Doorloop tijd (Customer Cycle Time) vertaling incompleet?

### ISSUE THREAD

**Issue by glaudia** [ScrumFacilitators/EBM-Gids-NL#9]
Is dit the complete vertaling? lijkt als het niet af is. 
 
![image](https://user-images.githubusercontent.com/52327049/104852604-da6ff680-58f3-11eb-9aa0-591f2a4aded0.png)

**Comment by sjoerdly** [comment]
fixed
